version: "3.9"

services:
  master:
    build: ./master
    container_name: master
    hostname: master
    privileged: true
    ports:
      - "2222:22"
    volumes:
      - ./ansible:/ansible
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    dns:
      - 172.20.0.13  # Dev DNS (node3)
      - 172.20.0.16  # Test DNS (node6)
      - 172.20.0.20  # Prod DNS (node10)
      - 8.8.8.8      # Fallback
    dns_search:
      - iticparis.dev
      - iticparis.test
      - iticparis.prod
    networks:
      ansible_net:
        ipv4_address: 172.20.0.10


  node1:
    build: ./node
    container_name: node1
    hostname: node1
    privileged: true
    ports:
      - "8443:443"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.11

  node2:
    build: ./node
    container_name: node2
    hostname: node2
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.12

  node3:
    build: ./node
    container_name: node3
    hostname: node3
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.13

  node4:
    build: ./node
    container_name: node4
    hostname: node4
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.14

  node5:
    build: ./node
    container_name: node5
    hostname: node5
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.15

  node6:
    build: ./node
    container_name: node6
    hostname: node6
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.16

  node7:
    build: ./node
    container_name: node7
    hostname: node7
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.17

  node8:
    build: ./node
    container_name: node8
    hostname: node8
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.18

  node9:
    build: ./node
    container_name: node9
    hostname: node9
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.19

  node10:
    build: ./node
    container_name: node10
    hostname: node10
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.20

  node11:
    build: ./node
    container_name: node11
    hostname: node11
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    networks:
      ansible_net:
        ipv4_address: 172.20.0.21

networks:
  ansible_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
        - subnet: 172.20.0.0/16
    internal: false
