##############################################
# ANSIBLE LAB INVENTORY
##############################################

# DEV ENVIRONMENT
[dev_web]
node1
node2

[dev_dns]
node3

[dev_nagios]
node4

[dev:children]
dev_web
dev_dns
dev_nagios


# TEST ENVIRONMENT
[test_web]
node5

[test_dns]
node6

[test_nagios]
node7

[test:children]
test_web
test_dns
test_nagios


# PROD ENVIRONMENT
[prod_web]
node8
node9

[prod_dns]
node10

[prod_nagios]
node11

[prod:children]
prod_web
prod_dns
prod_nagios


# SERVICE GROUPS (across all environments)
[web:children]
dev_web
test_web
prod_web

[dns:children]
dev_dns
test_dns
prod_dns

[nagios:children]
dev_nagios
test_nagios
prod_nagios


# GLOBAL VARIABLES
[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=/ansible/secrets/keys/id_rsa
ansible_python_interpreter=/usr/bin/python3
